version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: |
            echo 'export TAG=${CIRCLE_SHA1}' >> $BASH_ENV
            echo 'export IMAGE_NAME="perftest"' >> $BASH_ENV
            echo 'export DOCKER_ID=${CIRCLE_USERNAME}'>> $BASH_ENV
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $CIRCLE_USERNAME/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $CIRCLE_USERNAME/$IMAGE_NAME:$TAG