apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6-metrics
    user: admin
    secureJsonData:
      password: password123
    jsonData:
      version: Flux
      organization: k6-org
      defaultBucket: k6-metrics
      tlsSkipVerify: true
    isDefault: true
